### ISSUE TITLE
mining breakium makes tools dissapear

### ISSUE THREAD

**Issue by RCXcrafter** [diesieben07/Modjam-4#8]
When breakium is mined with a tinkers construct pickaxe the tool dissapears instead of turning into its broken state.
I'm guessing the same would happen to tools from forestry but I haven't tested that.

**Comment by diesieben07** [comment]
That is intentional, it breaks all tools.

**Comment by RCXcrafter** [comment]
Tinkers construct tools have a special broken state so that they can be repaired after breaking, that's what I meant. Some tools from forestry also have that.

**Comment by diesieben07** [comment]
This mod is called Bad Ores. And it's only not called Shitty Ores because the Modjam people did not like that name.
The ores are supposed to be annoying and shitty. This is intentional.

**Comment by RCXcrafter** [comment]
Okay, I didn't think it was intentional because in the book dissapearing was only one of three possible things that could happen to your pickaxe.
